# Generated by Django 5.2.8 on 2025-11-27 13:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09156308230', help_text='شماره موبایل برای ورود با OTP استفاده می\u200cشود.', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید بین ۱۰ تا ۱۵ رقم و فقط شامل عدد باشد (با امکان شروع با +).', regex='^\\+?\\d{10,15}$')]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='شماره موبایل باید بین ۱۰ تا ۱۵ رقم و فقط شامل عدد باشد (با امکان شروع با +).', regex='^\\+?\\d{10,15}$')])),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('verify_phone', 'تأیید شماره')], default='login', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کدهای یکبار مصرف',
                'indexes': [models.Index(fields=['phone_number', 'purpose'], name='accounts_on_phone_n_afc44e_idx')],
            },
        ),
    ]
